### ISSUE TITLE
How to get credit card number before (or) after payment? 

### ISSUE THREAD

**Issue by balaji-subramaniyam** [vy-group/ionic-stripe-checkout#8]
Hi @amilamen , I just use this npm. I have a doubt that how to get the card number before or after the payment. I get the **exp_Month**, **exp_Year**, and only the **last four digit of the card number** not full number from stripe charges api. Is there any option to get full card number? 
I will wait for your positive reply.
Thanks in advance

**Comment by amilamen** [comment]
Hello @balaji-subramaniyam,
Sorry for late. The card number is entered by the user and it is for security that Stripe only gives you the last digits.
What do you want to do with the full card number?

**Comment by balaji-subramaniyam** [comment]
Thanks for your response. Actually I need the card details to be saved after the successful payment except **cvv** number.
Otherwise every time the user need to enter the card number to make payment. Is there any possibility that the user can use the existing card for payment?

**Comment by ChafikHadjAbdouRazack** [comment]
Hi @balaji-subramaniyam 
For this purpose you need to use the stripe api for retrive the card belong a customer. Or save the payment method token in your database belong a customer.
For create payment method: https://stripe.com/docs/api/payment_methods/create
For retrive payment method : https://stripe.com/docs/api/payment_methods/retrieve

**Comment by amilamen** [comment]
> Thanks for your response. Actually I need the card details to be saved after the successful payment except **cvv** number. Otherwise every time the user need to enter the card number to make payment. Is there any possibility that the user can use the existing card for payment?

Hi @balaji-subramaniyam,
I better understand your problem. For actual version of package, you can't retrieve card informations.
I'll make an update of package to allow developer to get these informations.
Stay connected for next version and thank you for your relevant issue.

**Comment by balaji-subramaniyam** [comment]
Thank you **@ChafikHadjAbdouRazack** and **@amilamen**  for your reply and suggestions.

**Comment by amilamen** [comment]
@balaji-subramaniyam package has been updated !
